---
# Сервисная учетная запись для администратора кластера.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apo-admin-user
  namespace: default
---
# Сервисная учетная запись для инженера поддержки
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apo-deployer-user
  namespace: development
---
# Сервисная учетная запись для разработчика
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apo-developer-user
  namespace: development
---
# Сервисная учетная запись для инженера безопасности
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apo-security-user
  namespace: development
